version: "3.9"

services:
  web2:
    build: .
    container_name: django_web_2
    volumes:
      - .:/app
    ports:
      - "8002:8002"
    env_file:
      - .env
    depends_on:
      - db2
      - redis

  db2:
    image: postgres:16
    container_name: postgres_db_2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  redis:
    image: redis:7-alpine
    container_name: redis_2
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    container_name: celery_worker_2
    command: sh -c "sleep 5 && celery -A core worker -l info"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web2
      - redis

  celery_beat:
    build: .
    container_name: celery_beat_2
    command: sh -c "sleep 5 && celery -A core beat -l info"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web2
      - redis

volumes:
  postgres_data:




# version: "3.9"

# services:
#   web2:
#     build: .
#     container_name: django_web_2
#     volumes:
#       - .:/app
#     ports:
#       - "8002:8002"
#     env_file:
#       - .env
#     depends_on:
#       - db2

#   db2:
#     image: postgres:16
#     container_name: postgres_db_2
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_DB: ${DB_NAME}
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_PASSWORD: ${DB_PASSWORD}

# volumes:
#   postgres_data:
