version: '3.9'

services:
  db2:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - app

  redis2:
    image: redis:7-alpine
    restart: always
    networks:
      - app

  adminer2:
    image: adminer2
    restart: always
    depends_on:
      - db2
    ports:
      - "${ADMINER_PORT}:8080"
    networks:
      - app

  web2:
    build: .
    command: python manage.py runserver 0.0.0.0:8002
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "${PORT}:8002"
    depends_on:
      - db2
      - redis2
    networks:
      - app
    restart: always

  celery_worker:
    build: .
    command: celery -A core worker -l info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db2
      - redis2
    networks:
      - app
    restart: always

  celery_beat:
    build: .
    command: celery -A core beat -l info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db2
      - redis2
    networks:
      - app
    restart: always

networks:
  app:

volumes:
  pgdata:




# version: "3.9"

# services:
#   web2:
#     build: .
#     container_name: django_web_2
#     volumes:
#       - .:/app
#     ports:
#       - "8002:8002"
#     env_file:
#       - .env
#     depends_on:
#       - db2

#   db2:
#     image: postgres:16
#     container_name: postgres_db_2
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_DB: ${DB_NAME}
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_PASSWORD: ${DB_PASSWORD}

# volumes:
#   postgres_data:
